name: cvpr2023_env
channels:
- https://conda.anaconda.org/menpo
- conda-forge
dependencies:
- python=3.8
- openmpi
- openexr
- pip
- pip:
  - timm
  - torch
  - torchvision
  - wandb
  - webdataset
  - certifi
  - ctypes-callable
  - cycler
  - fonttools
  - glfw
  - kiwisolver
  - matplotlib
  - numpy
  - opencv-python
  - packaging
  - Pillow
  - plydata
  - plyfile
  - protobuf
  - PyGLM
  - PyOpenGL
  - PyOpenGL-accelerate
  - pyparsing
  - PySDL2
  - pysdl2-dll
  - python-dateutil
  - pytz
  - six
  - tqdm
  - open3d
  - noise
